# Generated by Django 4.1.2 on 2022-11-05 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_zone', '0002_productproperty_productsales_generaldata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generaldata',
            options={'verbose_name': 'Osobní údaje'},
        ),
        migrations.AlterModelOptions(
            name='productproperty',
            options={'verbose_name': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='productsales',
            options={'verbose_name': 'Prodeje produktů'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Uživatel'},
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='building_number',
            field=models.CharField(max_length=200, verbose_name='Číslo popisné'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Název firmy'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='country',
            field=models.CharField(max_length=200, verbose_name='Země'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='register_id',
            field=models.CharField(max_length=200, verbose_name='IČO'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='street',
            field=models.CharField(max_length=200, verbose_name='Ulice'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='telephone_number',
            field=models.CharField(max_length=200, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='vat_id',
            field=models.CharField(max_length=200, verbose_name='DIČ'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='zip_code',
            field=models.CharField(max_length=200, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Název produktu'),
        ),
        migrations.AlterField(
            model_name='productsales',
            name='expiration_date',
            field=models.DateTimeField(verbose_name='Datum expirace'),
        ),
        migrations.AlterField(
            model_name='productsales',
            name='order_date',
            field=models.DateTimeField(verbose_name='Datum objednávky'),
        ),
        migrations.AlterField(
            model_name='productsales',
            name='payment_date',
            field=models.DateTimeField(verbose_name='Datum platby'),
        ),
        migrations.AlterField(
            model_name='productsales',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user_zone.productproperty', verbose_name='Název produktu'),
        ),
        migrations.AlterField(
            model_name='productsales',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=300, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
    ]
